(ns net.wikipunk.rdf.fibo-bp-iss-doc
  "Ontology containing concepts about types of documentation that are used, referred to or generated by aspects of securities issuance processes."
  {:cmns-av/copyright "Copyright (c) 2013-2023 EDM Council, Inc.",
   :dcat/downloadURL
   "https://spec.edmcouncil.org/fibo/ontology/BP/SecuritiesIssuance/IssuanceDocuments/",
   :dcterms/abstract
   "Ontology containing concepts about types of documentation that are used, referred to or generated by aspects of securities issuance processes.",
   :dcterms/license {:rdfa/uri "https://opensource.org/licenses/MIT"},
   :fibo-fnd-utl-av/hasMaturityLevel :fibo-fnd-utl-av/Provisional,
   :owl/imports
   [{:rdfa/uri
     "https://spec.edmcouncil.org/fibo/ontology/master/latest/FND/Relations/Relations/"}
    {:rdfa/uri
     "https://spec.edmcouncil.org/fibo/ontology/master/latest/FND/Agreements/Contracts/"}
    {:rdfa/uri "https://www.omg.org/spec/Commons/DatesAndTimes/"}
    {:rdfa/uri
     "https://spec.edmcouncil.org/fibo/ontology/master/latest/FND/Law/LegalCore/"}
    {:rdfa/uri
     "https://spec.edmcouncil.org/fibo/ontology/master/latest/SEC/Securities/SecuritiesIssuance/"}
    {:rdfa/uri
     "https://spec.edmcouncil.org/fibo/ontology/master/latest/FND/Utilities/AnnotationVocabulary/"}
    {:rdfa/uri "https://www.omg.org/spec/Commons/AnnotationVocabulary/"}],
   :owl/versionIRI
   {:rdfa/uri
    "https://spec.edmcouncil.org/fibo/ontology/master/latest/BP/SecuritiesIssuance/IssuanceDocuments/"},
   :rdf/ns-prefix-map
   {"cmns-av" "https://www.omg.org/spec/Commons/AnnotationVocabulary/",
    "cmns-dt" "https://www.omg.org/spec/Commons/DatesAndTimes/",
    "dcterms" "http://purl.org/dc/terms/",
    "fibo-bp-iss-doc"
    "https://spec.edmcouncil.org/fibo/ontology/BP/SecuritiesIssuance/IssuanceDocuments/",
    "fibo-fnd-agr-ctr"
    "https://spec.edmcouncil.org/fibo/ontology/FND/Agreements/Contracts/",
    "fibo-fnd-utl-av"
    "https://spec.edmcouncil.org/fibo/ontology/FND/Utilities/AnnotationVocabulary/",
    "fibo-sec-sec-iss"
    "https://spec.edmcouncil.org/fibo/ontology/SEC/Securities/SecuritiesIssuance/",
    "owl" "http://www.w3.org/2002/07/owl#",
    "rdf" "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs" "http://www.w3.org/2000/01/rdf-schema#",
    "skos" "http://www.w3.org/2004/02/skos/core#",
    "xsd" "http://www.w3.org/2001/XMLSchema#"},
   :rdf/type :owl/Ontology,
   :rdfa/prefix "fibo-bp-iss-doc",
   :rdfa/uri
   "https://spec.edmcouncil.org/fibo/ontology/BP/SecuritiesIssuance/IssuanceDocuments/",
   :rdfs/label #xsd/langString "IssuanceDocuments@en"})

(def FinalProspectus
  "The final Prospectus for an issue describes the Offer Issue, including facts about the issue itself such as closing dates, and known facts about the securities that will form part of that issue."
  {:cmns-av/explanatoryNote
   #xsd/langString
    "Anticipated facts might include expected issue price, yields, pool parameters as appropriate for the type of instrument being issued. Term origin:SMER@en",
   :db/ident :fibo-bp-iss-doc/FinalProspectus,
   :rdf/type :owl/Class,
   :rdfs/isDefinedBy
   {:rdfa/uri
    "https://spec.edmcouncil.org/fibo/ontology/BP/SecuritiesIssuance/IssuanceDocuments/"},
   :rdfs/label #xsd/langString "final prospectus@en",
   :rdfs/subClassOf
   [{:owl/onProperty     :cmns-dt/succeeds,
     :owl/someValuesFrom :fibo-bp-iss-doc/PreliminaryProspectus,
     :rdf/type           :owl/Restriction}
    {:owl/onProperty     :fibo-fnd-agr-ctr/hasContractualElement,
     :owl/someValuesFrom :fibo-bp-iss-doc/OfferingDocumentTerms,
     :rdf/type           :owl/Restriction}
    :fibo-sec-sec-iss/Prospectus],
   :skos/definition
   #xsd/langString
    "The final Prospectus for an issue describes the Offer Issue, including facts about the issue itself such as closing dates, and known facts about the securities that will form part of that issue.@en"})

(def Indenture
  "A written contract, also known as a \"Deed of Trust\", under which bonds and debentures are issued, setting forth maturity date, interest rate, redemption rights, call privileges and other terms. Under the rules of the Trust Indenture Act of 1939, the contract is executed by the issuer and a trustee who acts on behalf of the bondholders."
  {:db/ident :fibo-bp-iss-doc/Indenture,
   :rdf/type :owl/Class,
   :rdfs/isDefinedBy
   {:rdfa/uri
    "https://spec.edmcouncil.org/fibo/ontology/BP/SecuritiesIssuance/IssuanceDocuments/"},
   :rdfs/label #xsd/langString "indenture@en",
   :rdfs/subClassOf [:fibo-fnd-agr-ctr/WrittenContract
                     :fibo-bp-iss-doc/SecuritiesIssuanceAgreement
                     {:owl/onProperty :fibo-fnd-agr-ctr/hasContractualElement,
                      :owl/someValuesFrom
                      :fibo-bp-iss-doc/OfferingDocumentTerms,
                      :rdf/type :owl/Restriction}
                     :fibo-sec-sec-iss/OfferingDocument],
   :skos/definition
   #xsd/langString
    "A written contract, also known as a \"Deed of Trust\", under which bonds and debentures are issued, setting forth maturity date, interest rate, redemption rights, call privileges and other terms. Under the rules of the Trust Indenture Act of 1939, the contract is executed by the issuer and a trustee who acts on behalf of the bondholders.@en"})

(def IssuanceTrustAgreement
  "issuance trust agreement"
  {:db/ident :fibo-bp-iss-doc/IssuanceTrustAgreement,
   :rdf/type :owl/Class,
   :rdfs/isDefinedBy
   {:rdfa/uri
    "https://spec.edmcouncil.org/fibo/ontology/BP/SecuritiesIssuance/IssuanceDocuments/"},
   :rdfs/label #xsd/langString "issuance trust agreement@en",
   :rdfs/subClassOf [:fibo-fnd-agr-ctr/WrittenContract
                     :fibo-bp-iss-doc/SecuritiesIssuanceAgreement
                     {:owl/onProperty :fibo-fnd-agr-ctr/hasContractualElement,
                      :owl/someValuesFrom
                      :fibo-bp-iss-doc/OfferingDocumentTerms,
                      :rdf/type :owl/Restriction}
                     :fibo-sec-sec-iss/OfferingDocument]})

(def OfferingDocumentTerms
  "terms included in an offering document that become legally binding at issue"
  {:cmns-av/explanatoryNote
   #xsd/langString
    "They include, for example, call terms, interest payment terms, and so forth with respect to certain securities.@en",
   :db/ident :fibo-bp-iss-doc/OfferingDocumentTerms,
   :rdf/type :owl/Class,
   :rdfs/isDefinedBy
   {:rdfa/uri
    "https://spec.edmcouncil.org/fibo/ontology/BP/SecuritiesIssuance/IssuanceDocuments/"},
   :rdfs/label #xsd/langString "offering document terms@en",
   :rdfs/subClassOf :fibo-fnd-agr-ctr/ContractualElement,
   :skos/definition
   #xsd/langString
    "terms included in an offering document that become legally binding at issue@en"})

(def PreliminaryProspectus
  "The draft prospectus for the issue, as determined prior to marketing the issue. Certain terms in the draft prospectus will be finalized later in the issuance process to become the actual Prospectus. Term origin:DTCC issuance Reviews"
  {:db/ident :fibo-bp-iss-doc/PreliminaryProspectus,
   :rdf/type :owl/Class,
   :rdfs/isDefinedBy
   {:rdfa/uri
    "https://spec.edmcouncil.org/fibo/ontology/BP/SecuritiesIssuance/IssuanceDocuments/"},
   :rdfs/label #xsd/langString "preliminary prospectus@en",
   :rdfs/subClassOf [{:owl/onProperty :fibo-fnd-agr-ctr/hasContractualElement,
                      :owl/someValuesFrom
                      :fibo-bp-iss-doc/OfferingDocumentTerms,
                      :rdf/type :owl/Restriction}
                     :fibo-sec-sec-iss/Prospectus],
   :skos/definition
   #xsd/langString
    "The draft prospectus for the issue, as determined prior to marketing the issue. Certain terms in the draft prospectus will be finalized later in the issuance process to become the actual Prospectus. Term origin:DTCC issuance Reviews@en"})

(def SecuritiesIssuanceAgreement
  "A formal agreement, deed or contract in respect of some intended securities issuance."
  {:db/ident :fibo-bp-iss-doc/SecuritiesIssuanceAgreement,
   :rdf/type :owl/Class,
   :rdfs/isDefinedBy
   {:rdfa/uri
    "https://spec.edmcouncil.org/fibo/ontology/BP/SecuritiesIssuance/IssuanceDocuments/"},
   :rdfs/label #xsd/langString "securities issuance agreement@en",
   :rdfs/subClassOf [:fibo-sec-sec-iss/OfferingDocument
                     {:owl/onProperty :fibo-fnd-agr-ctr/hasContractualElement,
                      :owl/someValuesFrom
                      :fibo-bp-iss-doc/OfferingDocumentTerms,
                      :rdf/type :owl/Restriction}],
   :skos/definition
   #xsd/langString
    "A formal agreement, deed or contract in respect of some intended securities issuance.@en"})